[project]
authors = [{ name = "KevinNitroG" }, { name = "NTGNguyen" }]
description = "Check phạt nguội"
name = "check-phat-nguoi"
version = "0.1.0-dev.1"
requires-python = "==3.13.*"
dynamic = ["dependencies"]

[project.scripts]
check-phat-nguoi = "check_phat_nguoi:main"
generate-config-schema = "generate_config_schema:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = { file = "requirements.txt" }
