[project]
name = 'check-phat-nguoi'
version = "0.1.0-dev.1"
dependencies = ["requests == 2.32.2", "pydantic == 2.10.4"]

[project.scripts]
check-phat-nguoi = "check_phat_nguoi:main"
generate-config-schema = "generate_config_schema:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
