name: Schedule Run
on:
  # schedule:
  #   - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      config: ${{ secrets.config }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
          cache-dependency-path: '**/requirements.txt'

      - name: Install deps
        run: pip install .

      - name: Restore config
        if: ${{ env.config != '' }}
        shell: bash
        run: curl -o config.json ${{ env.config }}

      - name: Run
        run: check-phat-nguoi
